# Logo Url
# Please enter an absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo: //img.alicdn.com/tps/TB1Nv_wKXXXXXbmXVXXXXXXXXXX-295-195.png

# Header
menu:
  # Delete this row if you don't want categories in your header nav bar
  Web开发: /categories/Web开发/
  Node.js: /categories/Node-js/
  无线开发: /categories/无线开发/
  工具&平台: /categories/工具-平台/
  团队生活: /categories/团队生活/
  关于我们: /about/

# Article list grouped by year
groupByYear: true

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
sidebar: left # sidebar's position (left or right)
social_links:
  rss: /atom.xml
widgets:
- recent_posts
- category
- archive
# - tag
#- tagcloud
- links

# Links
links:
  淘宝UED: http://ued.taobao.org/blog/
  Node地下铁: http://www.nodejs.club/

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: false

# Miscellaneous
google_analytics: UA-65944345-1
favicon: /favicon.ico
fb_admins:
fb_app_id: